### ISSUE TITLE
Missing source/repo for callstats, fmj, jnsapi

### ISSUE THREAD

**Issue by champtar** [jitsi/jitsi-maven-repository#3]
Hi,

i'm trying to build all jitsi code from source (to have reproducible build)

If I exclude ```github.com/jitsi/jitsi-maven-repository/raw/master/releases``` and ```repo.maven.apache.org/maven2```, i still don't have the source code for the following artifacts:
```
callstats/callstats/0.0.1-SNAPSHOT
org/xmpp/jnsapi/0.0.3-jitsi-1-SNAPSHOT
org/jitsi/fmj/1.0-SNAPSHOT
```

**Comment by lyubomir** [comment]
The source code of these projects is at, respectively:
https://github.com/callstats-io/callstats.java
https://github.com/jitsi/jinglenodes/tree/jitsi
http://sourceforge.net/p/fmj/code/HEAD/tree/fmj/

**Comment by champtar** [comment]
Hi @lyubomir,

Can you setup a git mirror of fmj svn to github?
I need a git repo for my git submodules, and prefer to host it under jitsi org.

To make a one time import you can just go to https://import.github.com/new, and import http://svn.code.sf.net/p/fmj/code/fmj/
(i'm only importing fmj dir so jitsi-universe relative path in pom.xml is ok)

For now i've made my own https://github.com/champtar/fmj-sourceforge-mirror
